stages:
  - service-java
  - service-python

cache:
  paths:
    - .m2/repository 
    - service-java/service-java-main/target/
    - venv/

variables:
  MAVEN_XML_PATH: "services/service-java-main/pom.xml"
  MAVEN_REPOSITORY: "-Dmaven.repo.local=.m2/repository"

  

service-java:
  
  stage: service-java
  image: maven:3.9.9-eclipse-temurin-23-alpine

  script:
    - echo "Compilation du projet..."
    - mvn compile -f $MAVEN_XML_PATH $MAVEN_REPOSITORY
    - echo "Exécution des tests"
    - mvn test -f $MAVEN_XML_PATH $MAVEN_REPOSITORY

   
    

# service-python:
  
#   stage: service-python
#   image: python:3.8
  
#   before_script:
#     - python -m venv venv
#     - source venv/bin/activate
#     - cd ./service-python/service-python-main
#     - pip install -r requirements.txt
    
#   script:
#     - echo "Exécution des tests"
#     - python test_app.py
