stages:
  - service-java
  - service-python
  - build-and-deploy

# Création des dossiers pour la mise en cache du runner
cache:
  paths:
    - .m2/repository 
    - service-java/service-java-main/target/
    - venv/

# Définition des variables Maven pour optimiser la mise en cache.
variables:
  MAVEN_XML_PATH: "service-java/service-java-main/pom.xml" # emplacement du pom.xml principal
  MAVEN_REPOSITORY: "-Dmaven.repo.local=.m2/repository" # un répertoire local de dépendances
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"


  

service-java:
  
  stage: service-java
  image: maven:3.9.9-eclipse-temurin-23-alpine

  script:
    - echo "Compilation du projet..."
    - mvn compile -f $MAVEN_XML_PATH $MAVEN_REPOSITORY # récupère les dépendances dans le cache ou bien stockent les dépendances lors de la première execution
    - echo "Exécution des tests"
    - mvn test -f $MAVEN_XML_PATH $MAVEN_REPOSITORY

   
    

service-python:
  
  stage: service-python
  image: python:3.8

  before_script:

    - python -m venv venv
    - source venv/bin/activate
    - cd ./service-python/service-python-main
    - pip install -r requirements.txt 
    
  script:
    - echo "Exécution des tests"
    - python test_app.py

build-and-deploy:
  stage: build-and-deploy
  image: docker:24.0.2
  
  services:
    - docker:24.0.2-dind
  
  dependencies:
    - service-java
    - service-python
  
  before_script:
     - echo $REGISTRY_PASSWORD | docker login $REGISTRY_URL -u $USERNAME --password-stdin
     - docker --version
 

  script:


    - echo "Déploiement de l'infra sur Azure"



    - echo "Build et push de l'image service-java"
    - docker build -t $REGISTRY_URL/service-java:latest ./service-java/service-java-main
    - docker push $REGISTRY_URL/service-java:latest


    - echo "Build et push de l'image service-python"
    - docker build -t $REGISTRY_URL/service-python:latest ./service-python/service-python-main
    - docker push $REGISTRY_URL/service-python:latest








