stages:
  - service-java
  - service-python

cache:
  paths:
    - service-java/service-java-main/target/
    - venv/

  

service-java:
  
  stage: service-java
  image: maven:3.9.9-eclipse-temurin-23-alpine

  before_script: 
    - cd ./service-java/service-java-main
  script:
    - echo "Compilation du projet..."
    - mvn compile
    - echo "Exécution des tests"
    - mvn test
   
    

service-python:
  
  stage: service-python
  image: python:3.8
  
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - cd ./service-python/service-python-main
    - pip install -r requirements.txt
    
  script:
    - echo "Exécution des tests"
    - python test_app.py
